name: driver-mouth
labels:
  - docker-image
dependencies:
  - fw-mouth: fw-files
  - artie-base-image: docker-image
  - open-ocd-image: docker-image
artifacts:
  - name: docker-image
    type: docker-image
type: build
steps:
  - job: docker-build
    artifacts:
      - docker-image
    img-base-name: artie-mouth-driver
    buildx: true
    dockerfile-dpath: "${REPO_ROOT}/drivers/mouth-and-eyebrows"
    dockerfile: Dockerfile
    build-context: "."
    dependency-files:
      - dependency:
          name: fw-files
          producing-task: fw-mouth
          match: ".+\\.elf"
    build-args:
      - DRIVER_TYPE: mouth
      - FW_FILE_NAME:
          dependency:
            name: fw-files
            producing-task: fw-mouth
            match: ".+\\.elf"
      - RPC_PORT: 4243
      - GIT_TAG: ${GIT_TAG}
      - ARTIE_BASE_IMG:
          dependency:
            name: docker-image
            producing-task: artie-base-image
      - OPENOCD_IMG:
          dependency:
            name: docker-image
            producing-task: open-ocd-image
