name: mouth-driver-integration-tests
labels:
  - docker-image
  - integration
dependencies:
  - mouth-driver-sanity-tests: ""
  - container-mouth: docker-image
  - container-reset: docker-image
  - log-collector: docker-image
  - metrics-collector: docker-image
  - artie-cli: docker-image
type: test
steps:
  - job: docker-compose-test-suite
    compose-fname: compose.driver-mouth.yaml
    compose-docker-image-variables:
      - RESET_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: container-reset
      - MOUTH_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: container-mouth
      - LOG_COLLECTOR_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: log-collector
      - METRICS_COLLECTOR_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: metrics-collector
    cli-image:
      dependency:
        name: docker-image
        producing-task: artie-cli
    steps:
      - test-name: init-mcu
        cmd-to-run-in-cli: "artie-cli help"
        expected-outputs:
          - what: "Writing 0x1 to "
            where: mouth-itest-reset-driver
          - what: "Mocking MCU FW load."
            where: mouth-itest-mouth-driver
      - test-name: fw-load
        cmd-to-run-in-cli: "artie-cli mouth fw load"
        expected-outputs:
          - what: "Writing 0x1 to "
            where: mouth-itest-reset-driver
          - what: "Mocking MCU FW load."
            where: mouth-itest-mouth-driver
