name: pico-base-image
labels:
  - docker-image
  - base-image
dependencies: ""
artifacts:
  - name: docker-image
    type: docker-image
type: build
steps:
  - job: docker-build
    artifacts:
      - docker-image
    img-base-name: pico-base
    buildx: false
    dockerfile-dpath: "${REPO_ROOT}/libraries/base-image"
    dockerfile: Dockerfile.pico
    build-context: "."
