name: fw-reset
labels:
  - firmware
dependencies:
  - pico-base-image: docker-image
artifacts:
  - name: docker-image
    type: docker-image
  - name: fw-files
    type: fw-files
type: build
steps:
  - job: docker-build
    artifacts:
      - docker-image
    img-base-name: artie-reset
    buildx: false
    dockerfile-dpath: "${REPO_ROOT}/firmware/reset/build"
    dockerfile: Dockerfile
    build-context: ".."
    build-args:
      - ARTIE_BASE_IMG:
          dependency:
            name: docker-image
            producing-task: pico-base-image
  - job: file-transfer-from-container
    artifacts:
      - fw-files
    image:
      dependency:
        name: docker-image
        producing-task: fw-reset
    fw-files-in-container:
      - /pico/src/build/reset-mcu.elf
      - /pico/src/build/reset-mcu.hex
      - /pico/src/build/reset-mcu.bin
      - /pico/src/build/reset-mcu.uf2
