name: artie-cli
labels:
  - docker-image
dependencies: ""
artifacts:
  - name: docker-image-amd64
    type: docker-image
  - name: docker-image-arm64
    type: docker-image
  - name: docker-image
    type: docker-manifest
type: build
steps:
  - job: docker-build
    artifacts:
      - docker-image-amd64
    img-base-name: artie-cli
    buildx: true
    platform: linux/amd64
    dockerfile-dpath: "${REPO_ROOT}/cli/test"
    dockerfile: Dockerfile
    build-context: ".."
  - job: docker-build
    artifacts:
      - docker-image-arm64
    img-base-name: artie-cli
    buildx: true
    platform: linux/arm64
    dockerfile-dpath: "${REPO_ROOT}/cli/test"
    dockerfile: Dockerfile
    build-context: ".."
  - job: docker-manifest
    artifacts:
      - docker-image
    img-base-name: artie-cli
    images:
      - dependency:
          name: docker-image-amd64
          producing-task: artie-cli
      - dependency:
          name: docker-image-arm64
          producing-task: artie-cli
