name: telemetry-integration-test
networks:
  telemetry-itest:
    external: true

services:
  reset-driver:
    command: python main.py /conf/mcu-fw.elf --port 18861 --loglevel info
    container_name: telemetry-itest-reset-driver
    depends_on:
      - log-collector
    expose:
      - 18861
    networks:
      - telemetry-itest
    image: ${RESET_TEST_IMAGE}
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090

  eyebrows-driver:
    command: python -m src.main /conf/mcu-fw.elf --port 18863 --loglevel info
    container_name: telemetry-itest-eyebrows-driver
    depends_on:
      - reset-driver
      - log-collector
    image: ${EYEBROWS_TEST_IMAGE}
    expose:
      - 18863
    networks:
      - telemetry-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090

  log-collector:
    container_name: telemetry-itest-log-collector
    image: ${LOG_COLLECTOR_TEST_IMAGE}
    expose:
      - 5170
    networks:
      - telemetry-itest

  metrics-collector:
    container_name: telemetry-itest-metrics-collector
    image: ${METRICS_COLLECTOR_TEST_IMAGE}
    depends_on:
      - eyebrows-driver
      - reset-driver
      - artie-api-server
    environment:
      - TEST_ENV=1
    networks:
      - telemetry-itest

  artie-api-server:
    container_name: telemetry-itest-api-server
    image: ${ARTIE_API_SERVER_TEST_IMAGE}
    depends_on:
      - eyebrows-driver
      - reset-driver
      - log-collector
    expose:
      - 8782
    networks:
      - telemetry-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - PORT=8782
