"""
All the machinery for the status command.
"""
from .. import common
from .. import hw_config
from .. import kube
import argparse
import datetime
import enum
import json

class LogOptions(enum.Enum):
    """Options for fetching logs along with status"""
    NONE = ("none", "Do not fetch logs.")
    ALL = ("all", "Fetch all logs pertaining to the status being queried.")
    GENERATED = ("generated", "Fetch only logs generated by the item whose status is being queried.")

class StatusFormatter:
    """Handles formatting of status output as either human-readable or JSON"""
    
    def __init__(self, use_json: bool, module: str, artie_name: str = None):
        self.use_json = use_json
        self.module = module
        self.artie_name = artie_name
        self.json_data = {
            "command": "status",
            "module": module,
            "timestamp": None,  # Filled in when we print
            "artie_name": artie_name,
            "success": True,
            "error": None,
            "data": {}
        }
   
    def add_data(self, item_type: str, item: dict):
        """Add status data to JSON output"""
        if 'item_type' not in self.json_data['data']:
            self.json_data["data"][item_type] = []

        self.json_data['data'][item_type].append(item)

    def output(self):
        """Output the final result"""
        # Fill in the timestamp
        self.json_data['timestamp'] = datetime.datetime.now().isoformat()

        if self.use_json:
            self._print_json()
        else:
            self._print_human()

    def set_data(self, item_type: str, items: list):
        """Set status data in JSON output."""
        self.json_data["data"][item_type] = items

    def set_error(self, error_message: str):
        """Set an error message"""
        self.json_data["success"] = False
        self.json_data["error"] = error_message
        self.json_data["data"] = None

    def _print_json(self):
        """Print, formatted as JSON."""
        print(json.dumps(self.json_data, indent=2))

    def _print_human(self):
        """Print, formatted for human readability."""
        errmsg = self.json_data['error']
        if errmsg is not None:
            common.error(errmsg)
            return

        match self.json_data['module']:
            case "nodes":
                self._print_human_nodes()
            case "pods":
                self._print_human_pods()
            case "mcus":
                self._print_human_mcus()
            case "actuators":
                self._print_human_actuators()
            case "sensors":
                self._print_human_sensors()
            case _:
                module = self.json_data['module']
                common.error(f"Unknown status module: {module}")

    def _print_human_actuators(self):
        """Print the actuator statuses for human consumption."""
        common.info("Actuators:")
        for actuator in self.json_data['data'].get('actuators', []):
            if 'status' in actuator:
                common.info(f"- {actuator['name']}:")
                common.info(f"  Status: {actuator['status']['status']}")
                common.info(f"  Message: {actuator['status']['message']}")
            else:
                # Just list the actuators
                common.info(f"- {actuator['name']}")

    def _print_human_mcus(self):
        """Print the MCU statuses for human consumption."""
        common.info("MCUs:")
        for mcu in self.json_data['data'].get('mcus', []):
            if 'heartbeat' in mcu:
                common.info(f"- {mcu['name']}:")
                common.info(f"  Status: {mcu['heartbeat']['status']}")
                common.info(f"  Message: {mcu['heartbeat']['message']}")
            else:
                # Just list the MCUs
                common.info(f"- {mcu['name']}")

    def _print_human_nodes(self):
        """Print the nodes statuses for human consumption."""
        common.info("Nodes:")
        for node in self.json_data['data'].get('nodes', []):
            if 'status' in node:
                common.info(f"- {node['name']}: {node['status']}")
            else:
                # Just list the nodes
                common.info(f"- {node['name']}")

    def _print_human_pods(self):
        """Print the pod statuses for human consumption."""
        common.info("Pods:")
        for pod in self.json_data['data'].get('pods', []):
            if 'status' in pod:
                common.info(f"- {pod['name']}: {pod['status']}")
                common.info(f"  Containers:")
                for container in pod['containers']:
                    common.info(f"  - {container['name']}:")
                    common.info(f"    State: {container['state']}")
                    common.info(f"    Restart Count: {str(container['restart_count'])}")
            else:
                # Just list the pods
                common.info(f"- {pod['name']}")

    def _print_human_sensors(self):
        """Print the sensor statuses for human consumption."""
        common.info("Sensors:")
        for sensor in self.json_data['data'].get('sensors', []):
            if 'status' in sensor:
                common.info(f"- {sensor['name']}:")
                common.info(f"  Status: {sensor['status']['status']}")
                common.info(f"  Message: {sensor['status']['message']}")

def _list_actuators(args, artie_hw_config: hw_config.HWConfig, formatter: StatusFormatter):
    """List all actuators for this Artie"""
    items = []
    for actuator in artie_hw_config.actuators:
        items.append({
            "name": actuator.name,
            "type": actuator.type,
            "bus": actuator.bus
        })

    formatter.set_data("actuators", items)

def _list_mcus(args, artie_hw_config: hw_config.HWConfig, formatter: StatusFormatter):
    """List all MCUs for this Artie"""
    items = []
    for mcu in artie_hw_config.mcus:
        items.append({
            "name": mcu.name,
            "buses": mcu.buses
        })
    
    formatter.add_list_data("mcus", items)

def _list_nodes(args, artie_hw_config: hw_config.HWConfig, formatter: StatusFormatter):
    """List all nodes for this Artie"""
    items = []
    for sbc in artie_hw_config.sbcs:
        items.append({
            "name": f"{sbc.name}-{args.artie_name}",
            "sbc_name": sbc.name
        })
    
    formatter.set_data("nodes", items)

def _list_pods(args, pods, formatter: StatusFormatter):
    """List all pods in the artie namespace"""
    items = []
    for pod in pods:
        items.append({
            "name": pod.metadata.name
        })
    
    formatter.set_data("pods", items)

def _list_sensors(args, artie_hw_config: hw_config.HWConfig, formatter: StatusFormatter):
    """List all sensors for this Artie"""
    items = []
    for sensor in artie_hw_config.sensors:
        items.append({
            "name": sensor.name,
            "type": sensor.type,
            "bus": sensor.bus
        })
    
    formatter.set_data("sensors", items)

def _print_actuator_status(args, actuator: hw_config.Actuator, formatter: StatusFormatter):
    """Print status information for a single actuator."""
    status = {
        "name": actuator.name,
        "type": actuator.type,
        "bus": actuator.bus,
        "status": {
            "status": "not_implemented",
            "message": "Requires CAN bus integration"
        }
    }

    formatter.add_data("actuators", status)

def _print_mcu_status(args, mcu: hw_config.MCU, formatter: StatusFormatter):
    """Print status information for a single MCU."""
    status = {
        "name": mcu.name,
        "buses": mcu.buses,
        "heartbeat": {
            "status": "not_implemented",
            "message": "Requires CAN bus integration"
        }
    }

    formatter.add_data("mcus", status)

def _print_node_status(args, node: hw_config.SBC, formatter: StatusFormatter):
    """Print status information for a single node"""
    node_name = f"{node.name}-{args.artie_name}"
    try:
        if kube.node_is_online(args, node_name):
            labels = kube.get_node_labels(args, node_name)
            role = labels.get(kube.ArtieK8sKeys.NODE_ROLE, "unknown")
            status = {
                "name": node_name,
                "status": "online",
                "role": role,
                "artie": args.artie_name,
                "labels": dict(labels)
            }
        else:
            status = {
                "name": node_name,
                "status": "offline",
                "role": "unknown",
                "artie": args.artie_name,
                "labels": {}
            }
    except Exception as e:
        status = {
            "name": node_name,
            "status": "error",
            "error": str(e),
            "artie": args.artie_name,
            "labels": {}
        }

    formatter.add_data("nodes", status)

def _print_pod_status(args, pod, formatter: StatusFormatter):
    """Print status information for a single pod."""
    status = {
        "name": pod.metadata.name,
        "namespace": pod.metadata.namespace,
        "status": pod.status.phase,
        "node": pod.spec.node_name,
        "containers": []
    }

    if pod.status.container_statuses:
        for container in pod.status.container_statuses:
            state = "unknown"
            if container.state:
                if container.state.running:
                    state = "running"
                elif container.state.waiting:
                    state = "waiting"
                elif container.state.terminated:
                    state = "terminated"
            
            status['containers'].append({
                "name": container.name,
                "ready": container.ready,
                "restart_count": container.restart_count,
                "state": state
            })
    
    formatter.add_data("pods", status)

def _print_sensor_status(args, sensor: hw_config.Sensor, formatter: StatusFormatter):
    """Print status information for a single sensor."""
    status = {
        "name": sensor.name,
        "type": sensor.type,
        "bus": sensor.bus,
        "status": {
            "operational": "not_implemented",
            "message": "Requires sensor integration"
        }
    }

    formatter.add_data("sensors", status)

def _get_actuators_status(args, artie_hw_config: hw_config.HWConfig, formatter: StatusFormatter):
    """Get status for actuator(s)"""
    if args.list:
        _list_actuators(args, artie_hw_config, formatter)
        return
    
    # Possibly get status for all actuators
    if args.actuator == "all":
        for actuator in artie_hw_config.actuators:
            _print_actuator_status(args, actuator, formatter)
        return

    # Get status for specific actuator
    actuator_found = False
    for actuator in artie_hw_config.actuators:
        if actuator.name == args.actuator:
            actuator_found = True
            _print_actuator_status(args, actuator, formatter)
            break
    
    if not actuator_found:
        actuator_names = [actuator.name for actuator in artie_hw_config.actuators]
        error_msg = f"Actuator '{args.actuator}' not found in hardware configuration. Available actuators: {actuator_names}"
        formatter.set_error(error_msg)

def _get_mcus_status(args, artie_hw_config: hw_config.HWConfig, formatter: StatusFormatter):
    """Get status for MCU(s)"""
    if args.list:
        _list_mcus(args, artie_hw_config, formatter)
        return
    
    # Possibly get status for all MCUs
    if args.mcu == "all":
        for mcu in artie_hw_config.mcus:
            _print_mcu_status(args, mcu, formatter)
        return

    # Get status for specific MCU
    mcu_found = False
    for mcu in artie_hw_config.mcus:
        if mcu.name == args.mcu:
            mcu_found = True
            _print_mcu_status(args, mcu, formatter)
            break
    
    if not mcu_found:
        mcu_names = [mcu.name for mcu in artie_hw_config.mcus]
        error_msg = f"MCU '{args.mcu}' not found in hardware configuration. Available MCUs: {mcu_names}"
        formatter.set_error(error_msg)

def _get_nodes_status(args, artie_hw_config: hw_config.HWConfig, formatter: StatusFormatter):
    """Get status for node(s)"""
    if args.list:
        _list_nodes(args, artie_hw_config, formatter)
        return
    
    # Possibly get status for all nodes
    if args.node == "all":
        for sbc in artie_hw_config.sbcs:
            _print_node_status(args, sbc, formatter)
        return

    # Get status for a specific node
    node_found = False
    for sbc in artie_hw_config.sbcs:
        if sbc.name == args.node:
            node_found = True
            _print_node_status(args, sbc, formatter)
            break

    if not node_found:
        node_names = [sbc.name for sbc in artie_hw_config.sbcs]
        error_msg = f"Node '{args.node}' not found in hardware configuration. Available nodes: {node_names}"
        formatter.set_error(error_msg)

def _get_pods_status(args, formatter: StatusFormatter):
    """Get status for pod(s)"""
    # Get all the pods regardless
    try:
        pods = kube.get_all_pods(args)
    except Exception as e:
        formatter.set_error(f"Error getting pod status: {e}")
        return

    if args.list:
        _list_pods(args, pods, formatter)
        return

    # Possibly get status for all pods
    if args.pod == "all":
        for pod in pods:
            _print_pod_status(args, pod, formatter)
        return

    # Get status for a specific pod
    pod_found = False
    for pod in pods:
        if pod.metadata.name == args.pod:
            pod_found = True
            _print_pod_status(args, pod, formatter)
            break

    if not pod_found:
        pod_names = [pod.metadata.name for pod in pods]
        error_msg = f"Pod '{args.pod}' not found in Kubernetes. Available pods: {pod_names}"
        formatter.set_error(error_msg)

def _get_sensors_status(args, artie_hw_config: dict, formatter: StatusFormatter):
    """Get status for sensor(s)"""
    if args.list:
        _list_sensors(args, artie_hw_config, formatter)
        return
    
    # Possibly get status for all sensors
    if args.sensor == "all":
        for sensor in artie_hw_config.sensors:
            _print_sensor_status(args, sensor, formatter)
        return

    # Get status for specific sensor
    sensor_found = False
    for sensor in artie_hw_config.sensors:
        if sensor.name == args.sensor:
            sensor_found = True
            result = _print_sensor_status(args, sensor, formatter)
            break
    
    if not sensor_found:
        sensor_names = [sensor.name for sensor in artie_hw_config.sensors]
        error_msg = f"Sensor '{args.sensor}' not found in hardware configuration. Available sensors: {sensor_names}"
        formatter.set_error(error_msg)

def status(args):
    """
    Top-level status function.
    """
    retcode = 0

    # Create formatter based on --json flag
    formatter = StatusFormatter(use_json=args.json, module=args.module)

    # For pods, we don't need HW config
    if args.module == "pods":
        _get_pods_status(args, formatter)
        formatter.output()
        return retcode

    # Otherwise, access the Artie cluster to determine what type of Artie we have
    try:
        # After this call, `args` will have `artie_name` populated
        artie_hw_config = kube.get_artie_hw_config(args)
    except ValueError as e:
        formatter.set_error(f"Cannot get Artie's HW configuration: {str(e)}")
        formatter.output()
        retcode = 1
        return retcode
    except KeyError as e:
        formatter.set_error(f"Cannot get Artie's HW configuration: {str(e)}")
        formatter.output()
        retcode = 1
        return retcode

    match args.module:
        case "nodes":
            _get_nodes_status(args, artie_hw_config, formatter)
        case "mcus":
            _get_mcus_status(args, artie_hw_config, formatter)
        case "actuators":
            _get_actuators_status(args, artie_hw_config, formatter)
        case "sensors":
            _get_sensors_status(args, artie_hw_config, formatter)
        case _:
            formatter.set_error(f"Unknown status module: {args.module}")
            retcode = 1

    formatter.output()
    return retcode

def fill_subparser(parser_status: argparse.ArgumentParser, parent: argparse.ArgumentParser):
    subparsers = parser_status.add_subparsers(title="status-module", description="Choose what status to get")

    # Args that are useful for all status commands
    option_parser = argparse.ArgumentParser(parents=[parent], add_help=False)
    group = option_parser.add_argument_group("Status", "Status Options")
    group.add_argument("--json", action='store_true', help="If given, we format the output in JSON according to `status-command-api.md`")
    group.add_argument("--logs", choices=[option.value[0] for option in LogOptions], default=LogOptions.NONE.value[0], help=f"Whether to fetch logs along with status. Chooses from: {list(zip([option.value[0] for option in LogOptions], [option.value[1] for option in LogOptions]))} (default: {LogOptions.NONE.value[0]})")
    group.add_argument("--list", action='store_true', help="If given, we will list the available items instead of getting status for a specific item.")

    # Add all the status tasks
    node_parser = subparsers.add_parser("nodes", parents=[option_parser])
    node_parser.add_argument("node", default="all", type=str, help="The node to get status for. If not given, we get the status for all nodes.")
    node_parser.set_defaults(cmd=status, module="nodes")

    pod_parser = subparsers.add_parser("pods", parents=[option_parser])
    pod_parser.add_argument("pod", default="all", type=str, help="The pod to get status for. If not given, we get the status for all pods.")
    pod_parser.set_defaults(cmd=status, module="pods")

    mcu_parser = subparsers.add_parser("mcus", parents=[option_parser])
    mcu_parser.add_argument("mcu", default="all", type=str, help="The MCU to get heartbeat status for. If not given, we get the status for all MCUs.")
    mcu_parser.set_defaults(cmd=status, module="mcus")

    actuator_parser = subparsers.add_parser("actuators", parents=[option_parser])
    actuator_parser.add_argument("actuator", default="all", type=str, help="The actuator to get status for. If not given, we get the status for all actuators.")
    actuator_parser.set_defaults(cmd=status, module="actuators")

    sensor_parser = subparsers.add_parser("sensors", parents=[option_parser])
    sensor_parser.add_argument("sensor", default="all", type=str, help="The sensor to get status for. If not given, we get the status for all sensors.")
    sensor_parser.set_defaults(cmd=status, module="sensors")
