name: log-collector
labels:
  - docker-image
  - telemetry
dependencies: ""
artifacts:
  - name: docker-image-amd64
    type: docker-image
  - name: docker-image-arm64
    type: docker-image
  - name: docker-image
    type: docker-manifest
type: build
steps:
  - job: docker-build
    artifacts:
      - docker-image-amd64
    img-base-name: artie-log-collector
    buildx: true
    platform: linux/amd64
    dockerfile-dpath: "${REPO_ROOT}/libraries/telemetry/fluent-bit-log-collector"
    dockerfile: Dockerfile
    build-context: "."
  - job: docker-build
    artifacts:
      - docker-image-arm64
    img-base-name: artie-log-collector
    buildx: true
    platform: linux/arm64
    dockerfile-dpath: "${REPO_ROOT}/libraries/telemetry/fluent-bit-log-collector"
    dockerfile: Dockerfile
    build-context: "."
  - job: docker-manifest
    artifacts:
      - docker-image
    img-base-name: artie-log-collector
    images:
      - dependency:
          name: docker-image-amd64
          producing-task: log-collector
      - dependency:
          name: docker-image-arm64
          producing-task: log-collector
