name: 'Set up Artie Base'
description: 'Set up the basic requirements for Artie builds'
runs:
  using: "composite"
  steps:
    - id: python
      name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - id: install
      name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - id: qemu
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - id: buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
