name: logging-integration-test
networks:
  logging-itest:
    external: true

services:
  reset-driver:
    command: python main.py /conf/mcu-fw.elf --port 18861 --loglevel info
    container_name: logging-itest-reset-driver
    depends_on:
      - log-collector
    expose:
      - 18861
    networks:
      - logging-itest
    image: ${RESET_TEST_IMAGE}
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090

  eyebrows-driver:
    command: python main.py /conf/mcu-fw.elf --port 18863 --loglevel info
    container_name: logging-itest-eyebrows-driver
    depends_on:
      - reset-driver
      - log-collector
    image: ${EYEBROWS_TEST_IMAGE}
    expose:
      - 18863
    networks:
      - logging-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090

  log-collector:
    container_name: log-collector
    image: ${LOG_COLLECTOR_TEST_IMAGE}
    expose:
      - 5170
    networks:
      - logging-itest

  artie-api-server:
    container_name: logging-itest-api-server
    image: ${ARTIE_API_SERVER_TEST_IMAGE}
    depends_on:
      - eyebrows-driver
      - reset-driver
      - log-collector
    expose:
      - 8782
    networks:
      - logging-itest
    environment:
      - ARTIE_RUN_MODE=integration
      - LOG_COLLECTOR_HOSTNAME=log-collector
      - LOG_COLLECTOR_PORT=5170
      - METRICS_SERVER_PORT=8090
      - PORT=8782
