name: telemetry-integration-tests
labels:
  - docker-image
  - integration
dependencies:
  - container-eyebrows: docker-image
  - container-reset: docker-image
  - log-collector: docker-image
  - metrics-collector: docker-image
  - artie-cli: docker-image
type: test
steps:
  - job: docker-compose-test-suite
    compose-fname: compose.telemetry.yaml
    compose-docker-image-variables:
      - RESET_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: container-reset
      - EYEBROWS_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: container-eyebrows
      - LOG_COLLECTOR_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: log-collector
      - METRICS_COLLECTOR_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: metrics-collector
    cli-image:
      dependency:
        name: docker-image
        producing-task: artie-cli
    steps:
      - test-name: init-mcu
        cmd-to-run-in-cli: "artie-cli help"
        expected-outputs:
          - what: "Writing 0x0 to "
            where: eyebrows-itest-reset-driver
          - what: "Writing 0x0 to "
            where: log-collector
          - what: "Mocking MCU FW load."
            where: eyebrows-itest-eyebrows-driver
          - what: "Mocking MCU FW load."
            where: log-collector
          - what: "Test Passed"
            where: metrics-collector
      - test-name: fw-load
        cmd-to-run-in-cli: "artie-cli eyebrows fw load"
        expected-outputs:
          - what: "Writing 0x0 to "
            where: eyebrows-itest-reset-driver
          - what: "Writing 0x0 to "
            where: log-collector
          - what: "Mocking MCU FW load."
            where: eyebrows-itest-eyebrows-driver
          - what: "Mocking MCU FW load."
            where: log-collector
