name: metrics-integration-tests
labels:
  - docker-image
  - integration
dependencies:
  - driver-eyebrows: docker-image
  - driver-reset: docker-image
  - metrics-collector: docker-image
  - artie-cli: docker-image
  - artie-api-server: docker-image
type: test
steps:
  - job: docker-compose-test-suite
    compose-fname: compose.metrics.yaml
    compose-docker-image-variables:
      - RESET_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: driver-reset
      - EYEBROWS_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: driver-eyebrows
      - METRICS_COLLECTOR_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: metrics-collector
      - ARTIE_API_SERVER_TEST_IMAGE:
          dependency:
            name: docker-image
            producing-task: artie-api-server
    cli-image:
      dependency:
        name: docker-image
        producing-task: artie-cli
    steps:
      - test-name: init-mcu
        cmd-to-run-in-cli: "artie-cli help"
        expected-outputs:
          - what: "Test Passed"
            where: metrics-collector
