name: reset-driver-sanity-tests
labels:
  - docker-image
  - sanity
dependencies:
  - container-reset: docker-image
type: test
steps:
  - job: single-container-sanity-suite
    steps:
      - test-name: start-reset-driver
        docker-image-under-test:
          dependency:
            name: docker-image
            producing-task: container-reset
        cmd-to-run-in-dut: "python main.py /conf/mcu-fw.elf --loglevel info --help"
