name: eyebrows-driver-hardware-tests
labels:
  - docker-image
  - hardware
dependencies:
type: test
steps:
  - job: hardware-test-suite
    steps:
      - test-name: hw-eyebrows
        cmd-to-run-in-cli: "artie-cli eyebrows status"
        expected-results:
          - "TODO"
