name: eyebrows-driver-unit-tests
labels:
  - docker-image
  - unit
dependencies:
  - eyebrows-driver-sanity-tests: ""
  - container-eyebrows: docker-image
  - artie-cli: docker-image
type: test
steps:
  - job: single-container-cli-suite
    docker-image-under-test:
      dependency:
        name: docker-image
        producing-task: container-eyebrows
    cmd-to-run-in-dut: "python main.py /conf/mcu-fw.elf --port 18863 --loglevel info"
    dut-port-mappings:
      - 18863: 18863
    cli-image:
      dependency:
        name: docker-image
        producing-task: artie-cli
    steps:
      - test-name: init-mcu
        cmd-to-run-in-cli: "artie-cli help"
        expected-outputs:
          - what: "Mocking MCU FW load."
            where: ${DUT}
      - test-name: led-on
        cmd-to-run-in-cli: "artie-cli eyebrows led on --side left"
        expected-outputs:
          - what: "left LED -> ON"
            where: ${DUT}
      - test-name: led-off
        cmd-to-run-in-cli: "artie-cli eyebrows led off --side right"
        expected-outputs:
          - what: "right LED -> OFF"
            where: ${DUT}
      - test-name: led-heartbeat
        cmd-to-run-in-cli: "artie-cli eyebrows led heartbeat --side both"
        expected-outputs:
          - what: "left LED -> HEARTBEAT"
            where: ${DUT}
      - test-name: lcd-test
        cmd-to-run-in-cli: "artie-cli eyebrows lcd test --side both"
        expected-outputs:
          - what: "right LCD -> TEST"
            where: ${DUT}
      - test-name: lcd-off
        cmd-to-run-in-cli: "artie-cli eyebrows lcd off --side left"
        expected-outputs:
          - what: "left LCD -> OFF"
            where: ${DUT}
      - test-name: lcd-draw
        cmd-to-run-in-cli: "artie-cli eyebrows lcd draw H H L --side left"
        expected-outputs:
          - what: "left LCD -> DRAW"
            where: ${DUT}
      - test-name: fw-load
        cmd-to-run-in-cli: "artie-cli eyebrows fw load"
        expected-outputs:
          - what: "Mocking MCU FW load."
            where: ${DUT}
      - test-name: servo-go
        cmd-to-run-in-cli: "artie-cli eyebrows servo go 45 --side right"
        expected-outputs:
          - what: "right SERVO -> GO"
            where: ${DUT}
